

server {
    listen 9000;
    root /app;
    server_name another.local;
    client_max_body_size 200M;

    error_page 404 /errorPages/404.html;
    location /index.html {
        index index.html;
        allowed_methods GET POST DELETE;
        autoindex on;
    }
    location /folder/ {
        autoindex on;
        allowed_methods GET POST DELETE;
    }
}

server {
    listen 9002;
    root /website;
    server_name another.local;
    client_max_body_size 200M;
    error_page 400 /errorPages/400.html;
    error_page 403 /errorPages/403.html;
    error_page 404 /errorPages/404.html;
    error_page 405 /errorPages/405.html;
    error_page 413 /errorPages/413.html;
    error_page 500 /errorPages/500.html;  

        location / {
            index index.html;
            autoindex on;
            allowed_methods GET POST DELETE;
        }


}

server {
    listen 9001;
    server_name cgi.local;
    root /app_copy;

    location /index.html {
        cgi_path test.py;
        cgi_interpreter /usr/bin/python3;
        index index.html;
        allowed_methods GET POST DELETE;
        autoindex on;
    }
}

